server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: SERPNT_BFF_SESSION
        same-site: none
        secure: true
  port: 8082
app:
  main-uri: ${MAIN_URI}
  backend-api-domain: ${BACKEND_API_DOMAIN:http://127.0.0.1:8081}
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:3000,https://serpnt.azotix.dev,https://*.netlify.app}
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: serpnt
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI}
            scope:
             - openid
             - profile
             - offline_access
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
